# Generated by Django 4.0.6 on 2023-03-31 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='fullname',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
