# Generated by Django 4.0.6 on 2023-03-31 14:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('review', '0002_rename_comment_review_message'),
    ]

    operations = [
        migrations.RenameField(
            model_name='review',
            old_name='message',
            new_name='comment',
        ),
    ]
