# Generated by Django 4.1.7 on 2023-03-03 14:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('voucher', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ('payment_name', models.CharField(blank=True, max_length=255)),
                ('payment_info', models.CharField(blank=True, max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('address', models.CharField(blank=True, max_length=255)),
                ('status', models.CharField(blank=True, choices=[('SUCCESS', 'SUCCESS'), ('FAILED', 'FAILED')], max_length=20)),
                ('amount', models.IntegerField(blank=True)),
                ('message', models.CharField(blank=True, max_length=255)),
                ('security_code', models.CharField(blank=True, max_length=15)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('payment', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='transaction.payment')),
                ('user', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('voucher', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='voucher.voucher')),
            ],
        ),
    ]
